services:
  darkshard:
    build: .
    image: shard
    ports:
      - "50051:50051"
    container_name: "shard"
    networks:
      - dardkshard_net
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    container_name: "rabbitmq"
    networks:
      - dardkshard_net
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5672 || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s

networks:
  dardkshard_net:
    driver: "bridge"
